package io.github.giansluca.jargs.exception;

public enum ErrorCode {
    INVALID_SCHEMA_ELEMENT_TYPE,
    EMPTY_SCHEMA_ELEMENT_NAME,
    INVALID_SCHEMA_ELEMENT_NAME,
    UNEXPECTED_ARGUMENT,
    INVALID_ARGUMENT_NAME,
    MISSING_STRING,
    MISSING_INTEGER,
    INVALID_INTEGER,
    MISSING_DOUBLE,
    INVALID_DOUBLE
}
